version: 1
clinics:
  - id: "kitchener-downtown"
    name: "QueueIQ Walk-in Kitchener Downtown"
    address_or_city: "Kitchener, ON"
    hours:
      mon: "09:00-17:00"
      tue: "09:00-17:00"
      wed: "09:00-17:00"
      thu: "09:00-17:00"
      fri: "09:00-17:00"
      sat: "10:00-14:00"
      sun: "closed"
    mock_capacity:
      servers_total: 3
      avg_service_minutes: 12

  - id: "waterloo-uptown"
    name: "QueueIQ Walk-in Waterloo Uptown"
    address_or_city: "Waterloo, ON"
    hours:
      mon: "10:00-18:00"
      tue: "10:00-18:00"
      wed: "10:00-18:00"
      thu: "10:00-18:00"
      fri: "10:00-18:00"
      sat: "closed"
      sun: "closed"
    mock_capacity:
      servers_total: 2
      avg_service_minutes: 14
